### ISSUE TITLE
"Source Sans" does not exist

### ISSUE THREAD

**Issue by mreyk** [Stanford-Online/lagunita-theme#58]
There is a bug with the `font-family` used.

I can see you're using a `font-family` named `"Source Sans"`:
https://github.com/Stanford-Online/lagunita-theme/blob/master/static/sass/_lagunita.scss#L70

But this `font-family` does not exist. So a different font-family will be loaded on the page depending on the web browser. You may have undesired behaviours as text overlapping.

So you may want to use another specific font-family.

**Comment by mreyk** [comment]
Fix in #59

**Comment by caesar2164** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Properly import "Crimson Text" : Fix font imports in lagunita theme](https://trello.com/c/BhnW1lct/928-properly-import-crimson-text-fix-font-imports-in-lagunita-theme)
